apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2022-05-09T04:45:39Z"
  generation: 3
  labels:
    app: apiserver
  name: apiserver
  namespace: reksu2
  resourceVersion: "2033728"
  uid: bbe04a9c-0c15-4880-b693-142c21ee00e2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: apiserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-05-09T10:22:57+05:30"
      creationTimestamp: null
      labels:
        app: apiserver
    spec:
      containers:
      - env:
        - name: spring.datasource.url
          value: jdbc:postgresql://postgres:5432/smartbankapp
        image: brainupgrade/sba-apiserver:1.0.0
        imagePullPolicy: IfNotPresent
        name: sba-apiserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-05-09T04:45:39Z"
    lastUpdateTime: "2022-05-09T04:52:59Z"
    message: ReplicaSet "apiserver-7bc88499b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-05-10T07:45:44Z"
    lastUpdateTime: "2022-05-10T07:45:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1